console.log("Hello world")

const GoogleSpreadsheet = require('../node_modules/google-spreadsheet')
const JWT = require('../node_modules/google-auth-library')

console.log("Hello world")


const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: "scout-2220-1@amplified-lamp-346220.iam.gserviceaccount.com",
    key: `-----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDcI5ri8B5uH94U
    oS62cffLpURpVp5OACP6xOMlBqhYBDAylNF/UImEXsI6XRmSEgUkIZtkR0P5udq8
    dlRdyG+DaX6auMzolRDv/SnZI2Ol9ESEpzdPxyzKHeiT2ax5Y2eMwrdMzLWAUwcn
    4htJvuXVyjBOkAPYCZ1v8enq1QfS7561bgLmrT3yjEJ52KqPLne1YNLOOQcvVo5B
    QMd3/t37U9O5S94hNLpmCf9zsjdBexfN94ocz8qCnxvNIvfipBJJt4a0sYFJhK+G
    yl3C77Pj3kN+yawE+naRjI4BpeB0P6Cz/5+6VukUd0OH9Gix6tFKlR+P7zTnbtFb
    9th2uNfTAgMBAAECggEAE8mO2wuQA1W8Tb4SklYFMC9p9PlTCm+AdxfVKQIDsMGo
    9BWkt8fCofzYguF/x72fQQOqUZBcVP6hNuPV/9thNqk4DD/vNJAYRnzK6FiCKlZz
    WuR4Qs9Zlc4BbATFYuCOBrzb4ryF1gPgi/O1gI1MYHP89UWEVZoWUOEoUFzsspzU
    1qKW766ZagZQyoQ9HnkgUeagnc68dOf+Y1OfWzUAiWPCvZ0+3tQUjm/aFEy+IB63
    jkXT0e9vKTz3sV19YPkrY0oADHchR6ftDM36nWABC+byM7TCsjj653CUbL10He95
    TbTP5eh2YbuB0ozEXBrSt9Vce0qva1SSj3FenAmwSQKBgQD/kWOiCJga5WCDU6+d
    NeQXhjyB1x1yO80z7thUdiTBmTNaHsKN1HwvhZN7NL0ow2rD/B7t8Os4MBwrfyTe
    i0ygO1EnuvWOYRvsnKBzi7NHfoVJ5UcBhRuAjegNy9ODQwUggrl5NhY6YqzfEqXU
    lxTzFTqOIOzqMhnXMpoEaKVv+QKBgQDcguHQqgp063H7VI6ZTRyfxorU1uP5UwlF
    bxi9kq4FIY7btsx6SJR/5zA3ZGsAy3uO22ICyrQ044XnbqDbnm2v7x9phc3OcSOK
    E7NQ6W1/VxJ32eMJdFyPzH0ZH2y87SnCYJ9+hc0stlvDGT7zyft5OnxMjeg5BUAX
    7ASzqVuRKwKBgQD7kyIRwgYBC+TawglwZzlV0uVDJv+skKOqSKaZVgdOsEF1qCv6
    M73fhc0tDjhapSs3K7tCnNLfZ7SDONCRZWyTmnCD/K12b69uVqw3scBUU35fxJwG
    KgJtpMNWuVtHrjSg0S5E3HI7HSFxIckuIV8U/sO6Xzz4OUNorD4isuSP+QKBgQDJ
    i2bRzVkZXEklqjdbrrtG3bTurCpaK6cBq3U1b+dWEUH9V6q06bmw3aGYP1P9uf4I
    qEOAwbzLylkNGnQzxy4B69EOJZnh4k7VWQRAI9pM1Uyv9poofg5L8F82ox5D35CX
    dLDSd4D8KQDd5SlAsZADUY1ieyGRXFckhjgV7ekfWQKBgQDhzXbrY4JB69tXWb5w
    +UaQy1FUXz0cHHYGM/fq7KAGBTxvrU5Plp8P0S06ZOPWEse1xYjEbsMqLV53/vwm
    CMG2FQVN6+eILsU4D/G7T21kyCKajEIFwQpX1sNAi0zzH+5IzDKP99Jave9k70oa
    GO6skzPjLPH3ppCXorDUQEiA0Q==
    -----END PRIVATE KEY-----
    `,
    scopes: [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive',
        'https://www.googleapis.com/auth/drive.readonly',
    ],
});

console.log("Hello world")


if (serviceAccountAuth) {console.log("Service account exists")}

const doc = new GoogleSpreadsheet('14h_mJ6Y2aCh06k1WqHcwK-xZQ2GZ4JbNEQ835QD2WEc', serviceAccountAuth);
console.log("Hello world")

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
await doc.updateProperties({ title: 'renamed doc' });


  
/////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////


let savedResults = [];
// localStorage.setItem("Saved-Results", null);


function isArray(myArray) {
    return myArray.constructor.toString().indexOf("Array") > -1;
  }

function submitResults(event) {
   
    let all = document.getElementsByTagName("*");
    let inputs = [];
    let results = [];

    for (let i=0, max=all.length; i < max; i++) {
        if (all[i].nodeName === "INPUT") {
            inputs.push(all[i]);
        }
    }

    for (let i = 0, max = inputs.length; i < max; i++) {
        results.push(inputs[i].value);
        inputs[i].value = "";
    }
  
    console.log(savedResults)
    console.log(typeof savedResults)

    if (isArray(savedResults)) {
        console.log("array is array")
        savedResults.push(results);
        localStorage.setItem("Saved-Results", savedResults);
    } else {
        console.log("array is not array")
        console.log(typeof savedResults)
        localStorage.setItem("Saved-Results", saved);
    }
    
}

function logResults() {
    let item = localStorage.getItem("Saved-Results")
    if (item) {
        item = [item]
        for (let i = 0, max = item.length; i < max; i++) {
            console.log(item[i]);
        }
    }
}

document.getElementById("endOfForm").addEventListener('click', submitResults);
document.getElementById("logResults").addEventListener('click', logResults);